---
services:
  mosquitto:
    image: eclipse-mosquitto
  solis-mqtt-to-web:
    #build: .
    image: ghcr.io/mkorthof/solis-to-web:latest:latest
    volumes:
      - ./config.py:/app/config.py
      - ./www:/app/www
    links:
      - mosquitto:mqtt-broker
